### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by JTanimations** [tzc-nydzsf/Game1-V4#3]
hello there tzc, maybe we can work together( i will probably be the animator)

JT(you know me right?)

**Comment by tzc-nydzsf** [comment]
but it seems that i don't need an animator :-(

**Comment by tzc-nydzsf** [comment]
it's just a console game.

**Comment by tzc-nydzsf** [comment]
and why don't you follow CHHHOCHHH(_Imaginary_ phy)（（（

**Comment by JTanimations** [comment]
？

**Comment by JTanimations** [comment]
i mean i do graphics

**Comment by tzc-nydzsf** [comment]
> i mean i do graphics

but i don't need graphics and i don't know how to put graphics in it actually

you see, i used

```
	printf("加载中……\n");
	getdata();
	printf("加载完毕\n");
	Sleep(500);
```

**Comment by tzc-nydzsf** [comment]
$test LaTeX$

**Comment by tzc-nydzsf** [comment]
it seems that i can't use LaTeX here :-( $test$

**Comment by tzc-nydzsf** [comment]
？？？why can i use it now

**Comment by tzc-nydzsf** [comment]
$\LaTeX$ $\TeX$ $\KaTeX$

**Comment by JTanimations** [comment]
？？？

**Comment by B-F-S** [comment]
> ？？？

@JTanimations 看上去很难把c++和python结合在一起qwq

**Comment by tzc-nydzsf** [comment]
> > ？？？
> 
> @JTanimations 看上去很难把c++和python结合在一起qwq

@B-F-S er1cma巨佬的timer原来是c++的，他调用音乐的那个函数需要加编译选项，然后他用的编译器和dev不太一样，没有找到编译选项，于是他把代码转成了python

但是我并不会python
